In [3]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [4]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [5]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

data * 10

In [7]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

# Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Array Creation Functions<br>
**array** <br>
*Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default*<br>
**asarray**<br>
*Convert input to ndarray, but do not copy if the input is already an ndarray*<br>
**arange**<br>
*Like the built-in range but returns an ndarray instead of a list*<br>
**ones,**<br>
*Produce an array of all ones with the given shape and dtype;*<br>
**ones_like**<br>
*ones_like takes another array and produces a ones array of the same shape and dtype*<br>
**zeros,**<br>
Like ones and ones_likebut producing arrays of 0s instead<br>
**zeros_like**<br>
**empty,**<br>
*Create new arrays by allocating new memory, but do not populate with any values like ones and zeros.*<br>
**empty_like**<br>
*zeros*<br>
**full,**<br>
*Produce an array of the given shape and dtype with all values set to the indicated “fill value”*<br>
**full_like**<br>
*full_like takes another array and produces a filled array of the same shape and dtype* <br>
**eye, identity** <br>
*Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)*<br>

# Data Types for ndarrays

In [29]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [30]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

# NumPy Data Types<br>
**int8, uint8** - i1, u1 *Signed and unsigned 8-bit (1 byte) integer types* <br>
**int16, uint16** - i2, u2 *Signed and unsigned 16-bit integer types* <br>
**int32, uint32** - i4, u4 *Signed and unsigned 32-bit integer types* <br>
**int64, uint64** - i8, u8 *Signed and unsigned 64-bit integer types* <br>
**float16** -  f2 *Half-precision floating point* <br>
**float32** - f4 or f *Standard single-precision floating point; compatible with C float* <br>
**float64** - f8 or d *Standard double-precision floating point; compatible with C double and Python float object* <br>

**float128** - f16 or g *Extended-precision floating point* <br>
**complex64,** - c8, c16, *Complex numbers represented by two 32, 64, or 128 floats, respectively* <br>
**complex128,** - c32 * <br>
**complex256** <br>
**bool** - ? *Boolean type storing True and False values* <br>
**object** - 0 *Python object type; a value can be any Python object* <br>
**string_** - S *Fixed-length ASCII string type (1 byte per character); for example, to create a string dtype with length 10, use'S10'* <br>
**unicode_** - U *Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_(e.g.,'U10')* <br>

In [34]:
arr = np.array([1,2,3,4,5])

In [35]:
arr.dtype

dtype('int64')

In [38]:
float_arr = arr.astype(np.float64)

In [39]:
float_arr

array([1., 2., 3., 4., 5.])

In [40]:
float_arr.dtype

dtype('float64')

In [41]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [42]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [44]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [46]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [47]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [48]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [50]:
int_array = np.arange(10)

In [51]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [52]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
zeros_uint32 = np.zeros(8, dtype= 'u4')

In [58]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# Arithmatic with NumPy Arrays

In [59]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [60]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [62]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [65]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [66]:
arr2 =np.array([[0., 4., 1.], [7., 2., 12]])

arr2

In [68]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

Range is exclusive of the last number

In [69]:
arr = np.arange(10)

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[5]

5

In [72]:
arr[5:8]

array([5, 6, 7])

In [73]:
arr[5:8] = 12

In [74]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [76]:
arr_slice = arr[5:8]

In [79]:
arr_slice

array([12, 12, 12])

In [80]:
arr_slice[1] = 12345

In [81]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [84]:
arr_slice[:]= 64

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [88]:
arr2d[2]

array([7, 8, 9])

In [89]:
arr2d[0][2]

3

In [90]:
arr2d[0,2]

3

In [95]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [96]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
old_values = arr3d[0].copy()

In [100]:
arr3d[0]= 42

In [101]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[0] = old_values

In [103]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr3d[1,0]

array([7, 8, 9])

In [106]:
x = arr3d[1,0]

In [107]:
x

array([7, 8, 9])