In [2]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

data * 10

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

# Creating ndarrays

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Array Creation Functions<br>
**array** <br>
*Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default*<br>
**asarray**<br>
*Convert input to ndarray, but do not copy if the input is already an ndarray*<br>
**arange**<br>
*Like the built-in range but returns an ndarray instead of a list*<br>
**ones,**<br>
*Produce an array of all ones with the given shape and dtype;*<br>
**ones_like**<br>
*ones_like takes another array and produces a ones array of the same shape and dtype*<br>
**zeros,**<br>
Like ones and ones_likebut producing arrays of 0s instead<br>
**zeros_like**<br>
**empty,**<br>
*Create new arrays by allocating new memory, but do not populate with any values like ones and zeros.*<br>
**empty_like**<br>
*zeros*<br>
**full,**<br>
*Produce an array of the given shape and dtype with all values set to the indicated “fill value”*<br>
**full_like**<br>
*full_like takes another array and produces a filled array of the same shape and dtype* <br>
**eye, identity** <br>
*Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)*<br>

# Data Types for ndarrays

In [21]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [22]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

# NumPy Data Types<br>
**int8, uint8** - i1, u1 *Signed and unsigned 8-bit (1 byte) integer types* <br>
**int16, uint16** - i2, u2 *Signed and unsigned 16-bit integer types* <br>
**int32, uint32** - i4, u4 *Signed and unsigned 32-bit integer types* <br>
**int64, uint64** - i8, u8 *Signed and unsigned 64-bit integer types* <br>
**float16** -  f2 *Half-precision floating point* <br>
**float32** - f4 or f *Standard single-precision floating point; compatible with C float* <br>
**float64** - f8 or d *Standard double-precision floating point; compatible with C double and Python float object* <br>

**float128** - f16 or g *Extended-precision floating point* <br>
**complex64,** - c8, c16, *Complex numbers represented by two 32, 64, or 128 floats, respectively* <br>
**complex128,** - c32 * <br>
**complex256** <br>
**bool** - ? *Boolean type storing True and False values* <br>
**object** - 0 *Python object type; a value can be any Python object* <br>
**string_** - S *Fixed-length ASCII string type (1 byte per character); for example, to create a string dtype with length 10, use'S10'* <br>
**unicode_** - U *Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_(e.g.,'U10')* <br>

In [25]:
arr = np.array([1,2,3,4,5])

In [26]:
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr

array([1., 2., 3., 4., 5.])

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [31]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [33]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [34]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [36]:
int_array = np.arange(10)

In [37]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [38]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
zeros_uint32 = np.zeros(8, dtype= 'u4')

In [40]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# Arithmatic with NumPy Arrays

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [42]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [47]:
arr2 =np.array([[0., 4., 1.], [7., 2., 12]])

arr2

In [48]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

Range is exclusive of the last number

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [53]:
arr[5:8] = 12

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([12, 12, 12])

In [57]:
arr_slice[1] = 12345

In [58]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [59]:
arr_slice[:]= 64

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [62]:
arr2d[2]

array([7, 8, 9])

In [63]:
arr2d[0][2]

3

In [64]:
arr2d[0,2]

3

In [65]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [66]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
old_values = arr3d[0].copy()

In [70]:
arr3d[0]= 42

In [71]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0] = old_values

In [73]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[1,0]

array([7, 8, 9])

In [75]:
x = arr3d[1,0]

In [76]:
x

array([7, 8, 9])

# Indexing with Slices

In [77]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [78]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [79]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Select the first two rows of arr2d <br>
<br>
XXX<br>
XXX<br>
000<br>
v

In [80]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

0XX<br>
0XX<br>
000<br>
v

In [81]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [85]:
lower_dim_slice = arr2d[1, :2]

In [86]:
lower_dim_slice.shape

(2,)

00X<br>
00X<br>
000<br>
v

In [87]:
arr2d[:2, 2]

array([3, 6])

X00<br>
X00<br>
X00<br>
v

In [88]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [89]:
arr2d[:2, 1:]= 0

In [90]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

<br><br><br>


0XX     EXPRESSION     SHAPE<br>
0XX     arr[:2,1]      (2,2)<br>
000<br><br><br>
000     arr[2]         (3,)<br>
000     arr[2, :]      (3,)<br>
XXX     arr[2:,:]      (1,3)<br><br><br>
XX0     arr[:, :2]     (3,2)<br>
XX0<br>
XX0<br><br><br>
000     arr[1, :2]     (2,)<br>
XX0     arr[1:2, :2]   (1,2)<br>
000

# Boolean Indexing

In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [94]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [95]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [96]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [97]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [98]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [99]:
data[names == 'Bob', 1:]

array([[7],
       [0]])

In [100]:
data[names == 'Bob', 1]

array([7, 0])

In [101]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [102]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [103]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [104]:
cond = names == 'Bob'

In [105]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Python keywords *and* , *or* do not work with Boolean arrays. Use *&* and | (or) instead.

In [106]:
mask = (names == 'Bob') | (names == 'Will')

In [107]:
mask

array([ True, False,  True,  True,  True, False, False])

In [108]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [109]:
data[data < 0] = 0

In [110]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [111]:
data[names != 'Joe'] = 7

In [112]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

# Fancy Indexing <br>
Copies into a new array, your array will be modified with this method. To create a dimensional array of 8 rows and 4 tables:

In [113]:
arr = np.zeros((8,4))

# Fancy Indexing 

In [114]:
for i in range(8):
    arr[i] = i

In [115]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Calling rows 4, 3, 0, and 6 in that order:

In [117]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Calling from the bottom 

In [118]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Filling same size with numbers 0-31

In [119]:
arr = np.arange(32).reshape((8,4))

This one has me stumped!

In [120]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [121]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [122]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [123]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [124]:
arr[[1,5,7,2], [0,3,1,2]]=0

In [125]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

# Transposing Arrays and Swapping Axes

In [126]:
arr = np.arange(15).reshape((3,5))

In [127]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [130]:
arr = np.array([[0,1,0], [1,2,-2], [6,3,2], [-1, 0, -1], [1,0,1]])

In [131]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

Compute inner matrix product for matrix computations using numpy.dot:

In [132]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

The infix operator also does matrix multiplication.

In [133]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [134]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
returns a view withou

In [136]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])